# Author: Steven Jonathan


**Install Library Needed for the HW**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sea
import matplotlib.pyplot as plt

**Check the software verson of the Numpy and the Pandas**

In [ ]:
np.__version__

'1.19.5'

In [ ]:
pd.__version__

'1.1.5'

**Download The Dataset Needed**

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


--2021-09-11 08:28:06--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M  --.-KB/s    in 0.06s   

2021-09-11 08:28:06 (24.7 MB/s) - ‘data.csv.2’ saved [1475504/1475504]



**Find The Average Price of Car**

In [ ]:
cars_data = pd.read_csv("data.csv")

In [ ]:
cars_data.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [ ]:
cars_Price = cars_data.loc[:,["Make", "MSRP"]]
cars_Price.head()

Make   MSRP
0  BMW  46135
1  BMW  40650
2  BMW  36350
3  BMW  29450
4  BMW  34500

In [ ]:
BMW_Price = cars_Price.loc[cars_Price["Make"] == "BMW"]
MSRP = BMW_Price["MSRP"]
print(MSRP)

0         46135
1         40650
2         36350
3         29450
4         34500
          ...  
11901     49700
11902     66350
11903    128000
11904    130000
11905    131500
Name: MSRP, Length: 334, dtype: int64


In [ ]:
print("The Price of BMW: ", MSRP.mean())

The Price of BMW:  61546.76347305389


**Missing Value for Engine HP (Car after 2015)**

In [ ]:
car_Engine_2015 = cars_data.loc[cars_data["Year"] >= 2015]

In [ ]:
car_Engine_2015.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
32  FIAT  124 Spider  2017  ...       26         819  27495
33  FIAT  124 Spider  2017  ...       26         819  24995
34  FIAT  124 Spider  2017  ...       26         819  28195
41   BMW    2 Series  2016  ...       23        3916  32850
42   BMW    2 Series  2016  ...       23        3916  38650

[5 rows x 16 columns]

In [ ]:
car_Engine_2015.replace("?", np.nan, inplace = True)
car_Engine_2015.head(5)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


Make       Model  Year  ... city mpg  Popularity   MSRP
32  FIAT  124 Spider  2017  ...       26         819  27495
33  FIAT  124 Spider  2017  ...       26         819  24995
34  FIAT  124 Spider  2017  ...       26         819  28195
41   BMW    2 Series  2016  ...       23        3916  32850
42   BMW    2 Series  2016  ...       23        3916  38650

[5 rows x 16 columns]

In [ ]:
missing_data = car_Engine_2015.isnull()
missing_data.head(5)

Make  Model   Year  ...  city mpg  Popularity   MSRP
32  False  False  False  ...     False       False  False
33  False  False  False  ...     False       False  False
34  False  False  False  ...     False       False  False
41  False  False  False  ...     False       False  False
42  False  False  False  ...     False       False  False

[5 rows x 16 columns]

In [ ]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    

Make
False    5995
Name: Make, dtype: int64

Model
False    5995
Name: Model, dtype: int64

Year
False    5995
Name: Year, dtype: int64

Engine Fuel Type
False    5995
Name: Engine Fuel Type, dtype: int64

Engine HP
False    5944
True       51
Name: Engine HP, dtype: int64

Engine Cylinders
False    5987
True        8
Name: Engine Cylinders, dtype: int64

Transmission Type
False    5995
Name: Transmission Type, dtype: int64

Driven_Wheels
False    5995
Name: Driven_Wheels, dtype: int64

Number of Doors
False    5990
True        5
Name: Number of Doors, dtype: int64

Market Category
False    4671
True     1324
Name: Market Category, dtype: int64

Vehicle Size
False    5995
Name: Vehicle Size, dtype: int64

Vehicle Style
False    5995
Name: Vehicle Style, dtype: int64

highway MPG
False    5995
Name: highway MPG, dtype: int64

city mpg
False    5995
Name: city mpg, dtype: int64

Popularity
False    5995
Name: Popularity, dtype: int64

MSRP
False    5995
Name: MSRP, dtype: int64



**Engine HP, Find & Replace Engine HP using Mean, and investigate if both have the same value befored and after missing number replaced by mean ?**

In [ ]:
cars_data.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [ ]:
engine_HP = cars_data["Engine HP"]
engine_HP.head()

0    335.0
1    300.0
2    300.0
3    230.0
4    230.0
Name: Engine HP, dtype: float64

In [ ]:
print("Average engine HP: ", round(engine_HP.mean()))

Average engine HP:  249


In [ ]:
cars_data.replace("?", np.nan, inplace = True)
missing_data = cars_data.isnull()
missing_data.head(5)

Make  Model   Year  ...  city mpg  Popularity   MSRP
0  False  False  False  ...     False       False  False
1  False  False  False  ...     False       False  False
2  False  False  False  ...     False       False  False
3  False  False  False  ...     False       False  False
4  False  False  False  ...     False       False  False

[5 rows x 16 columns]

In [ ]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    

Make
False    11914
Name: Make, dtype: int64

Model
False    11914
Name: Model, dtype: int64

Year
False    11914
Name: Year, dtype: int64

Engine Fuel Type
False    11911
True         3
Name: Engine Fuel Type, dtype: int64

Engine HP
False    11845
True        69
Name: Engine HP, dtype: int64

Engine Cylinders
False    11884
True        30
Name: Engine Cylinders, dtype: int64

Transmission Type
False    11914
Name: Transmission Type, dtype: int64

Driven_Wheels
False    11914
Name: Driven_Wheels, dtype: int64

Number of Doors
False    11908
True         6
Name: Number of Doors, dtype: int64

Market Category
False    8172
True     3742
Name: Market Category, dtype: int64

Vehicle Size
False    11914
Name: Vehicle Size, dtype: int64

Vehicle Style
False    11914
Name: Vehicle Style, dtype: int64

highway MPG
False    11914
Name: highway MPG, dtype: int64

city mpg
False    11914
Name: city mpg, dtype: int64

Popularity
False    11914
Name: Popularity, dtype: int64

MSRP
False    11914
N

In [ ]:
cars_data["Engine HP"].replace(np.nan, engine_HP.mean(), inplace=True)

In [ ]:
cars_data.replace("?", np.nan, inplace = True)
missing_data = cars_data.isnull()

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("") 

Make
False    11914
Name: Make, dtype: int64

Model
False    11914
Name: Model, dtype: int64

Year
False    11914
Name: Year, dtype: int64

Engine Fuel Type
False    11911
True         3
Name: Engine Fuel Type, dtype: int64

Engine HP
False    11914
Name: Engine HP, dtype: int64

Engine Cylinders
False    11884
True        30
Name: Engine Cylinders, dtype: int64

Transmission Type
False    11914
Name: Transmission Type, dtype: int64

Driven_Wheels
False    11914
Name: Driven_Wheels, dtype: int64

Number of Doors
False    11908
True         6
Name: Number of Doors, dtype: int64

Market Category
False    8172
True     3742
Name: Market Category, dtype: int64

Vehicle Size
False    11914
Name: Vehicle Size, dtype: int64

Vehicle Style
False    11914
Name: Vehicle Style, dtype: int64

highway MPG
False    11914
Name: highway MPG, dtype: int64

city mpg
False    11914
Name: city mpg, dtype: int64

Popularity
False    11914
Name: Popularity, dtype: int64

MSRP
False    11914
Name: MSRP, dtyp

In [ ]:
engine_HP = cars_data["Engine HP"]
print("Average engine HP: ", round(engine_HP.mean()))

Average engine HP:  249


**Sum of All Elements [ Roll Rolyce ]**

In [ ]:
select_Column = ["Engine HP", "Engine Cylinders", "highway MPG"]
roll_Royce = cars_data.loc[cars_data["Make"] == "Rolls-Royce",select_Column ]
roll_Royce.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [ ]:
x = roll_Royce.drop_duplicates()
x.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5279      563.0              12.0           20
7443      322.0              12.0           15

In [ ]:
x_array = np.array(x)

In [ ]:
XTX = np.matmul(x_array.T,x_array) #use this insted of numpy.multiply


In [ ]:
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


In [ ]:
XTX = np.linalg.inv(XTX)
print(XTX)

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


In [ ]:
print("Sum of the Matrix: ", XTX.sum())

Sum of the Matrix:  0.032212320677486125


**Implement Linear Regression**

In [ ]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [ ]:
XTX = np.matmul(XTX.T,x_array.T)

In [ ]:
w = np.matmul(XTX, y)

In [ ]:
print(w)

[ 0.19989598 31.02612262 31.65378877]
